menu:
    Home: /
    Archives: /archives/
    Tags: /tags/
    Weibo: http://weibo.com/jesseccchen
    GitHub: https://github.com/chenjiangsong

favicon: http://ob3wg7deo.bkt.clouddn.com/batman_1.png
logo: http://ob3wg7deo.bkt.clouddn.com/batman.png

# Comment
# e.g disqus: seansun
#disqus: seansun
duoshuo: chenjiangsong

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2015
